#-*- coding:utf-8 -*-
# Part of ChamsERP. See LICENSE file for full copyright and licensing details.

{
    'name': 'Nigerian Civil Service Payroll',
    'version': '1.0',
    'category': 'Human Resources',
    'sequence': 38,
    'description': """
    Payroll for a Nigerian State
    """,
    'website': 'http://www.chamsplc.com',
    'depends': [
        'hr',
        'hr_contract_state',
        'hr_transfer',
        'report_xlsx',
        'web_digital_sign',
    ],
    'external_dependencies': {
        'python': ['dateutil'],
    },
    'data': [
        'module_data.xml',                
        'hr_payroll_view.xml',   
        'hr_disciplinary_cron.xml',
        'hr_disciplinary_workflow.xml',
        'payroll_cron.xml',
        'generate_mda_payslips.xml',
        'payroll_report_cron.xml',
        'diff_cron.xml',
        'init_stats_cron.xml',
        'init_earn_dedt_cron.xml',
        'resolve_earn_dedt_cron.xml',
        'hr_earnded_upload_cron.xml',
        'hr_earnded_upload_workflow.xml',
        'hr_bvn_upload_cron.xml',
        'hr_bvn_upload_workflow.xml',
        'hr_designation_upload_cron.xml',
        'hr_designation_upload_workflow.xml',
        'hr_certificate_upload_cron.xml',
        'hr_certificate_upload_workflow.xml',
        'hr_jobdesc_upload_cron.xml',
        'hr_jobdesc_upload_workflow.xml',
        'hr_changereq_cron.xml',
        'hr_changereq_workflow.xml',
        'hr_demise_cron.xml',
        'hr_demise_workflow.xml',
        'hr_extension_cron.xml',
        'hr_extension_workflow.xml',
        'hr_loan_cron.xml',
        'hr_loan_workflow.xml',
        'hr_query_cron.xml',
        'hr_query_workflow.xml',
        'hr_termination_cron.xml',
        'hr_termination_workflow.xml',
        'hr_retirement_cron.xml',
        'hr_retirement_cron_init.xml',
        'hr_retirement_cron_auto.xml',
        'hr_retirement_workflow.xml',
        'hr_increment_cron.xml',
        'hr_increment_cron_auto.xml',
        'hr_increment_cron_next.xml',
        'hr_increment_workflow.xml',
        'security/hr_security.xml',
        'security/ir.model.access.csv',
        'views/payroll_report.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
